import type { UiDictionary } from "@/content/en/ui";

/**
 * Dutch shared-UI dictionary — draft, pending human review (#151).
 * Typed against the canonical English shape: a missing key is a type error.
 * Terminology follows content/nl/GLOSSARY.md; certification agency and
 * product names stay English.
 */
export const ui: UiDictionary = {
  skipToContent: "Direct naar inhoud",
  nav: {
    primaryLabel: "Hoofdmenu",
    mobileLabel: "Mobiel",
    openMenu: "Menu openen",
    closeMenu: "Menu sluiten",
    logoAlt: "Sea Saba-logo",
    bookNow: "Boek nu",
    items: {
      "/diving": "Duiken",
      "/dive-sites": "Duikstekken",
      "/courses": "Cursussen",
      "/plan-your-trip": "Plan je reis",
      "/about": "Over ons",
    },
  },
  footer: {
    headings: {
      plan: "Plan je reis",
      explore: "Ontdek",
      contact: "Contact",
      resources: "Handige links",
    },
    navLabels: {
      tripPlanning: "Links voor het plannen van je reis",
      siteNav: "Sitenavigatie",
      resources: "Reisinformatie",
    },
    planLinks: {
      whereToStay: "Overnachten",
      gettingHere: "Naar Saba reizen",
      whenToVisit: "Beste reistijd",
      whatToBring: "Wat neem je mee",
      goodToKnow: "Handig om te weten",
      partners: "Aanbevolen partners",
    },
    exploreLinks: {
      diveSites: "Duikstekken",
      diving: "Duiken",
      diveLog: "Duiklogboek",
      courses: "Cursussen",
      about: "Over ons",
      contact: "Contact",
    },
    resourceLinks: {
      travelInsurance: "Reisverzekering",
      travelInsuranceAria: "Sluit een reisverzekering af via DiveAssure, opent in een nieuw tabblad",
      diveInsurance: "Duikverzekering",
      diveInsuranceAria: "Sluit een kortlopende duikverzekering af via DAN, opent in een nieuw tabblad",
      faq: "FAQ",
      // Legal destinations stay English-only (#151) — the (Engels) suffix
      // makes that explicit instead of implying a Dutch legal text.
      terms: "Algemene voorwaarden (Engels)",
      privacy: "Privacybeleid (Engels)",
      cookiePolicy: "Cookiebeleid (Engels)",
    },
    phone: "Telefoon",
    whatsappAria: "Neem contact op met Sea Saba via WhatsApp, opent in een nieuw tabblad",
    cookieSettings: "Cookie-instellingen",
    copyrightSuffix: "Sea Saba, NV • The Bottom, Saba, Caribisch Nederland",
    languageSwitcherLabel: "Kies je taal",
  },
  hero: {
    headline: "Duik in het buitengewone.",
    taglineA: "Amper 13 km² boven water.",
    taglineB: "Daaronder ligt een van de meest bijzondere duikgebieden van het Caraïbisch gebied.",
    bookDiving: "Boek je duiken",
    planTrip: "Plan je reis",
    exploreSites: "Ontdek de duikstekken",
    trust: {
      established: "Opgericht",
      protectedWaters: "Beschermde wateren",
      reviews: "Google & TripAdvisor",
      reviewsMobile: "Beoordelingen",
    },
  },
  contactForm: {
    name: "Naam",
    namePlaceholder: "Je volledige naam",
    email: "E-mail",
    emailPlaceholder: "naam@voorbeeld.nl",
    inquiryType: "Onderwerp",
    inquiryTypePlaceholder: "Kies een onderwerp",
    groupCourses: "Cursussen",
    groupGeneral: "Algemeen",
    optional: "(optioneel)",
    preferWhatsapp: "Ik heb liever contact via WhatsApp",
    message: "Bericht",
    messagePlaceholder: "Vertel ons over je plannen, vragen of wat we verder moeten weten.",
    continueToEmail: "Verstuur via e-mail",
    continueToEmailAria: "Verstuur via e-mail",
    whatsappCta: "WhatsApp Sea Saba",
    whatsappAria: "Verstuur je aanvraag via WhatsApp",
    errors: {
      name: "Vul je naam in.",
      emailRequired: "Vul je e-mailadres in.",
      emailInvalid: "Vul een geldig e-mailadres in.",
      inquiryType: "Kies een onderwerp.",
      message: "Typ een bericht.",
    },
    handoff: {
      title: "Je e-mailapp opent met je aanvraag klaar om te verzenden.",
      bodyA: "Controleer het bericht en druk op Verzenden — het gaat naar",
      bodyB: "vanaf je eigen e-mailadres. Als er niets opent,",
      tryAgain: "probeer het opnieuw",
      bodyC: "of mail ons rechtstreeks op",
      bodyD: ". Je kunt alles hierboven eerst aanpassen — je wijzigingen blijven bewaard.",
      footnote:
        "Dit opent je e-mailapp met de aanvraag klaar om te verzenden — wij reageren per e-mail, meestal binnen een dag. WhatsApp is handig voor korte vragen.",
    },
    inquiries: {
      "try-scuba": { label: "Try Scuba", subject: "Aanvraag Try Scuba", partyLabel: "Aantal deelnemers" },
      "sdi-open-water": { label: "SDI Open Water Diver", subject: "Aanvraag SDI Open Water Diver", partyLabel: "Aantal cursisten" },
      "sdi-advanced-specialty": { label: "SDI Advanced & Specialty Training", subject: "Aanvraag SDI Advanced & Specialty Training", partyLabel: "Aantal cursisten" },
      "sdi-nitrox": { label: "SDI Nitrox Diver", subject: "Aanvraag SDI Nitrox Diver", partyLabel: "Aantal cursisten" },
      "sdi-rescue": { label: "SDI Rescue Diver", subject: "Aanvraag SDI Rescue Diver", partyLabel: "Aantal cursisten" },
      "sdi-divemaster": { label: "SDI Divemaster", subject: "Aanvraag SDI Divemaster", partyLabel: "Aantal cursisten" },
      "tdi-technical": { label: "TDI Technical Diving", subject: "Aanvraag TDI Technical Diving", partyLabel: "Aantal cursisten" },
      general: { label: "Algemene vraag", subject: "Algemene vraag" },
      "book-diving": { label: "Duiken boeken", subject: "Aanvraag duiken boeken", partyLabel: "Aantal duikers" },
      "course-inquiry": { label: "Cursusaanvraag", subject: "Cursusaanvraag", partyLabel: "Aantal cursisten" },
      "private-charter": { label: "Privécharter", subject: "Aanvraag privécharter", partyLabel: "Groepsgrootte" },
      "visiting-yacht": { label: "Aankomst per jacht / zeilboot", subject: "Aanvraag aankomst per jacht", partyLabel: "Aantal gasten" },
      "group-travel": { label: "Groepsreis", subject: "Aanvraag groepsreis", partyLabel: "Groepsgrootte" },
      "sunset-cruise": { label: "Sunsetcruise", subject: "Aanvraag sunsetcruise", partyLabel: "Aantal gasten" },
      "saba-lace": { label: "Saba Lace", subject: "Aanvraag Saba Lace", partyLabel: "Aantal deelnemers" },
      "jewelry-making": { label: "Sieraden maken", subject: "Aanvraag sieraden maken", partyLabel: "Aantal deelnemers" },
      "glass-art": { label: "Glaskunst", subject: "Aanvraag glaskunst", partyLabel: "Aantal deelnemers" },
      transportation: { label: "Vervoer", subject: "Aanvraag vervoer", partyLabel: "Groepsgrootte" },
      other: { label: "Overig", subject: "Overige aanvraag" },
    },
    fields: {
      whatsapp: { label: "WhatsApp-nummer", placeholder: "+31 6 1234 5678" },
      dates: { label: "Geplande reisdata", placeholder: "bijv. 10–17 maart 2027" },
      partySize: { label: "Aantal personen", placeholder: "1" },
      certification: { label: "Brevetniveau", placeholder: "bijv. Open Water, Advanced" },
      loggedDives: { label: "Gelogde duiken", placeholder: "bijv. 25" },
    },
    handoffMessage: {
      greeting: "Hallo Sea Saba, mijn naam is",
      interestedIn: "Ik heb interesse in",
      travelDates: "Mijn geplande reisdata zijn",
      certificationIs: "Mijn brevetniveau is",
      loggedDives: "Ik heb",
      loggedDivesSuffix: "gelogde duiken",
      emailHeader: "Aanvraag via de Sea Saba-website",
      labels: {
        name: "Naam",
        email: "E-mail",
        inquiry: "Onderwerp",
        preferredContact: "Voorkeur voor contact",
        whatsapp: "WhatsApp",
        dates: "Geplande reisdata",
        certification: "Brevetniveau",
        loggedDives: "Gelogde duiken",
        message: "Bericht",
      },
      emailFallbackSubject: "Aanvraag via website",
      preferredEmail: "E-mail",
      coursePrefill: "Stuur mij graag meer informatie over beschikbaarheid, planning en prijzen.",
    },
  },
  findSeaSaba: {
    caption: "Direct aan Fort Bay Harbor gelegen, waar elke duiktocht van Sea Saba begint.",
    tooltipName: "Sea Saba Dive Center",
    tooltipPlace: "Fort Bay Harbor",
    getDirections: "Routebeschrijving",
    getDirectionsAria: "Bekijk de route naar Sea Saba Dive Center in Google Maps, opent in een nieuw tabblad",
    pinAria: "Open Sea Saba Dive Center in Google Maps, opent in een nieuw tabblad",
    googleMaps: "Openen in Google Maps",
    googleMapsAria: "Open Sea Saba in Google Maps, opent in een nieuw tabblad",
    appleMaps: "Openen in Apple Maps",
    appleMapsAria: "Open Sea Saba in Apple Maps, opent in een nieuw tabblad",
    imageAlt: "De duikbasis van Sea Saba aan Fort Bay Harbor, Saba",
  },
  experienceSelector: {
    heading: "Wat kun je verwachten",
    subtext: "Kies een duikoptie om de planning van de dag te zien.",
    taxiPickup: "Sta klaar voor de taxi",
    lunchBreak: "Lunchpauze",
    footnote:
      "De pickuptijden zijn het moment waarop de taxi's beginnen — zorg dat je klaarstaat; de exacte aankomst hangt af van de route. Alle tijden zijn bij benadering en kunnen afwijken afhankelijk van de omstandigheden.",
    bringLunchTitle: "Neem je eigen lunch mee",
    bringLunchClassic:
      "Lunch is in Fort Bay Harbor niet altijd beschikbaar, dus neem iets mee voordat je komt. De trip loopt zonder stop door tot in de middag.",
    bringLunchTryScuba:
      "Lunch is in Fort Bay Harbor niet altijd beschikbaar, dus neem iets mee voordat je komt.",
    thirdDiveTitle: "Nog een derde duik?",
    thirdDiveBody:
      "Vraag naar een upgrade naar onze Triple Tank-optie voor een langere dag. Als je de derde duik toevoegt, is het verstandig een lunch mee te nemen — de dag loopt door tot na de normale lunchtijd en eten bij de haven is niet altijd beschikbaar.",
    pills: {
      classic: "Classic 2-Tank",
      advanced: "Advanced 2-Tank",
      afternoon: "Afternoon 1-Tank",
      snorkel: "Afternoon Snorkel",
      tryscuba: "Try Scuba",
    },
    steps: {
      classicDeparture: "Boot vertrekt vanuit {harbor} voor twee ontspannen duiken in het Saba Marine Park (~70 ft / 21 m)",
      advancedDeparture: "Boot vertrekt voor twee duiken (duik 1 tot ~110 ft / 33 m, duik 2 tot ~70 ft / 21 m)",
      afternoonDeparture: "Boot vertrekt voor één duik tot ~70 ft / 21 m",
      snorkelDeparture: "Boot vertrekt; snorkel aan de oppervlakte terwijl de duikers dieper gaan",
      tryScubaTheory: "Theorie en vaardigheden in beschermd water in {harbor}",
      tryScubaDive: "Vaart mee met de middagboot voor een begeleide duik op het rif",
      returnTo: "Terug in {harbor}",
    },
  },
  insurance: {
    travel: "Reisverzekering afsluiten",
    travelAria: "Sluit een reisverzekering af via DiveAssure, opent in een nieuw tabblad",
    shortTerm: "Kortlopende duikverzekering",
    shortTermAria: "Sluit een kortlopende duikverzekering af via DAN, opent in een nieuw tabblad",
  },
  notFound: {
    heading: "404",
    title: "Pagina niet gevonden",
    body: "De pagina die je zoekt bestaat niet of is verplaatst.",
    home: "Terug naar home",
    contact: "Contact opnemen",
  },
  contactPage: {
    defaultHeadline: "Contact",
    defaultSubtitle:
      "Vragen over duiken op Saba, cursusbeschikbaarheid of iets anders? We helpen je graag.",
    coursesSubtitle:
      "Vertel ons kort over je plannen, dan helpt ons team je de beste planning te kiezen.",
    visitHeading: "Bezoek Sea Saba",
    visitName: "Sea Saba Dive Center",
    phoneLabel: "Telefoon",
    whatsappLabel: "WhatsApp",
    emailLabel: "E-mail",
    planningHeading: "Je reis plannen?",
    planningBody:
      "Op zoek naar vluchten, veerdiensten, accommodaties, huurauto's, het weer, FAQ's of een reisverzekering?",
    planningCta: "Plan je reis →",
  },
};
